// タイプの英語名と日本語名のマッピング
export const typeNameMapping: Record<string, string> = {
  all: 'すべてのタイプ',
  normal: 'ノーマル',
  fire: 'ほのお',
  water: 'みず',
  electric: 'でんき',
  grass: 'くさ',
  ice: 'こおり',
  fighting: 'かくとう',
  poison: 'どく',
  ground: 'じめん',
  flying: 'ひこう',
  psychic: 'エスパー',
  bug: 'むし',
  rock: 'いわ',
  ghost: 'ゴースト',
  dragon: 'ドラゴン',
  dark: 'あく',
  steel: 'はがね',
  fairy: 'フェアリー',
};

// タイプのカラースタイル
export const typeColors: Record<string, { bg: string; text: string; border: string }> = {
  all: { bg: 'bg-gray-200', text: 'text-gray-800', border: 'border-gray-300' },
  normal: { bg: 'bg-gray-200', text: 'text-gray-800', border: 'border-gray-300' },
  fire: { bg: 'bg-red-100', text: 'text-red-800', border: 'border-red-300' },
  water: { bg: 'bg-blue-100', text: 'text-blue-800', border: 'border-blue-300' },
  electric: { bg: 'bg-yellow-100', text: 'text-yellow-800', border: 'border-yellow-300' },
  grass: { bg: 'bg-green-100', text: 'text-green-800', border: 'border-green-300' },
  ice: { bg: 'bg-cyan-100', text: 'text-cyan-800', border: 'border-cyan-300' },
  fighting: { bg: 'bg-orange-100', text: 'text-orange-800', border: 'border-orange-300' },
  poison: { bg: 'bg-purple-100', text: 'text-purple-800', border: 'border-purple-300' },
  ground: { bg: 'bg-amber-100', text: 'text-amber-800', border: 'border-amber-300' },
  flying: { bg: 'bg-indigo-100', text: 'text-indigo-800', border: 'border-indigo-300' },
  psychic: { bg: 'bg-pink-100', text: 'text-pink-800', border: 'border-pink-300' },
  bug: { bg: 'bg-lime-100', text: 'text-lime-800', border: 'border-lime-300' },
  rock: { bg: 'bg-stone-100', text: 'text-stone-800', border: 'border-stone-300' },
  ghost: { bg: 'bg-violet-100', text: 'text-violet-800', border: 'border-violet-300' },
  dragon: { bg: 'bg-blue-100', text: 'text-blue-800', border: 'border-blue-300' },
  dark: { bg: 'bg-gray-100', text: 'text-gray-800', border: 'border-gray-300' },
  steel: { bg: 'bg-slate-100', text: 'text-slate-800', border: 'border-slate-300' },
  fairy: { bg: 'bg-rose-100', text: 'text-rose-800', border: 'border-rose-300' },
};
